### ISSUE TITLE
Cannot run a sample of code

### ISSUE THREAD

**Issue by serejahh** [wangshengjia/VWInstantRun#1]
Hi. I get error messages every time. Kind of:

```
<unknown>:0: error: cannot load underlying module for 'CoreGraphics'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun -sdk macosx swiftc" to select the default OS X SDK installed with Xcode
```

When I run `xcrun -sdk macosx swiftc` it says:
`<unknown>:0: error: no input files`

Could you help me?

**Comment by wangshengjia** [comment]
For now, behind the scene, the code selected will be built by `xcrun swiftc` with importation of `Foundation` module, which means this plugin only support the API from `Foundation` module. This is why you got this error message when your code selected required the API from `CoreGraphics` module.

I'll try to figure out a way to make it support more standard modules.

**Comment by serejahh** [comment]
It happens even when I try to execute just `print()`

**Comment by tomassliz** [comment]
@serejahh Same for me. Another problem is that console output ignores color settings. So I have black text on black background.

**Comment by wangshengjia** [comment]
@serejahh This is weird, do you have more details ?

@tomassliz Color problem is true, I created an issue #3, working on it.

**Comment by adamstener** [comment]
I'm having the same issue with just print

**Comment by wangshengjia** [comment]
Just in case: you do not happen to have a debug area with black background color, right ?

Otherwise, could you provide some more details please?

**Comment by adamstener** [comment]
I do not.  Not sure what else to provide you with, I get that same error message when I try to run a method that just has a print statement in it.  No idea why it's referencing CoreGraphics, nothing in the file or the selection has anything to do with CoreGraphics.

**Comment by wangshengjia** [comment]
I've just merged the fix into master. The problem should be fixed. Could you give a try please?

**Comment by serejahh** [comment]
@wangshengjia Yay, print works. Thanks :+1:

**Comment by wangshengjia** [comment]
Cool ! :tada: :tada:
