### ISSUE TITLE
什么时候能支持OC啊

### ISSUE THREAD

**Issue by SecondDog** [wangshengjia/VWInstantRun#4]
什么时候能支持OC啊。

**Comment by wangshengjia** [comment]
Obj-C编译执行牵扯到main函数，比Swift要麻烦不少。不过我会尽快上一个略有限制但是相对简单的版本，好歹也算支持Obj-C了。

多谢支持。

**Comment by oit63** [comment]
+1

**Comment by wangshengjia** [comment]
增加了略有限制的OC支持（只能选择单独的一行或者多行代码，无法选择执行整个函数😂）。

合并到master了，重装下试试吧。🍻🎉
